name: Deploy

on:
  push:
    branches:
      - source

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      # Instalar dependencias
      - name: Install Dependencies
        run: npm install

      # Clonar y ejecutar scripts de instalación de repositorios
      - name: Checkout and Install Dependencies
        run: |
          repositories=(
            "champierre/ml2scratch"
            "champierre/posenet2scratch"
            "microbit-more/mbit-more-v2:stretch3"
            "champierre/tm2scratch"
            "champierre/tmpose2scratch"
            "tfabworks/xcx-g2s:stretch3"
            "champierre/scratch2maqueen"
            "champierre/handpose2scratch"
            "champierre/facemesh2scratch"
            "con3office/pasorich"
            "sugiura-lab/scratch3-qrcode"
            "champierre/speech2scratch"
            "champierre/ic2scratch"
            "NorifumiOgawa/iftttWebhooks"
            "Diego-Luna/microbitSerial"
            "bricklife/scratch-lego-bluetooth-extensions"
            "geolonia/x-geo-scratch"
            "ichiroc/chatgpt2scratch"
            "champierre/scratch2webserialapi"
          )
          for repo in "${repositories[@]}"; do
            IFS=':' read -r -a parts <<< "$repo"
            repo_path=${parts[0]}
            repo_ref=${parts[1]:-}
            repo_name=$(basename "$repo_path")
            if [ -n "$repo_ref" ]; then
              git clone -b "$repo_ref" --single-branch "https://github.com/$repo_path" "$repo_name"
            else
              git clone "https://github.com/$repo_path" "$repo_name"
            fi
            if [ -f "$repo_name/install.sh" ]; then
              sh "$repo_name/install.sh"
            fi
          done

      # Comandos de instalación específicos
      - name: Add GA Tracking Code
        run: sh ./stretch3/add_ga_tracking_code.sh

      - name: Build Project
        run: NODE_OPTIONS=--openssl-legacy-provider npm run build

      - name: Modify Index HTML
        run: sh ./stretch3/modify_index_html.sh

      # Despliegue en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          ssh_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
          publish_branch: master
